apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: questspace
spec:
  selector:
    app: questspace-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
