apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: questspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questspace-frontend
  template:
    metadata:
      labels:
        app: questspace-frontend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: frontend-container
          image: __VERSION__
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_URL
              value: questspace.fun
            - name: NODE_ENV
              value: production
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: questspace-nextauth-secret
                  key: nextauth-secret
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: questspace-google-secret
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: questspace-google-secret
                  key: google-oauth-secret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: questspace-s3-secret
                  key: access-key-id
            - name: AWS_SECRET_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: questspace-s3-secret
                  key: secret-key-id
